{{- $namespace := .Values.global.namespace.name -}}
{{- range $serviceName,$webService :=  .Values.webServices }}
{{- if $webService.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  annotations:
    {{- if eq $webService.ingress.ingressClass "alb" }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:460468186850:certificate/3e3149ec-e6ba-4d5c-8afc-ea419fc93045
    alb.ingress.kubernetes.io/security-groups: sg-0ce6b3bc6361a0510
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:us-east-1:460468186850:regional/webacl/myplant-staging-WAF/9d6c75d1-bfdf-4995-8473-1bfef570590d
    {{- end }}
    {{- if eq $webService.ingress.ingressClass "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- if $webService.ingress.ingressAnnotations }}
    {{- range $key, $value := $webService.ingress.ingressAnnotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
  labels:
    app: {{ $serviceName }}
spec:
  ingressClassName: {{ $webService.ingress.ingressClass }}
  rules:
    {{- range $rule := $webService.ingress.rules }}
    - host: {{ $rule.host }}
      http:
        paths:
          {{- range $path := $rule.paths }}
          - path: {{ $path.path }}
            pathType: {{ default "ImplementationSpecific" $path.pathType }}
            backend:
              service:
                name: {{ $path.backend.service.name }}
                port:
                  {{- if int $path.backend.service.port }}
                  number: {{ $path.backend.service.port }}
                  {{- else }}
                  name: {{ $path.backend.service.port }}
                  {{- end }}
          {{- end }}
    {{- end }}

---
{{- end }}
{{- end }}